version: '3.4'
services:
  # #Need to remove the "SecurityFilter.java" check to make the application be available on the root of the url.
  # proxy:
  #   image: neqsim-proxy
  #   build: ./proxy
  #   ports:
  #     - "80:80"

  neqsimweb:
    container_name: neqsim-web
    hostname: neqsim-web
    image: neqsimweb
    env_file:
      - .secrets
    environment:
      MYSQL_USER: remote
      MYSQL_URL: jdbc:mysql://neqsim-db:3306/neqsimdatabase
      NEQSIMTHERMODB_CS: jdbc:mysql://thermo-db:3306/neqsimthermodatabase?useSSL=false
      NEQSIMBLOBDB_CS: jdbc:mysql://fluidblob-db:3306/neqsimblobdb?useSSL=false
    build: .
    ports:
      - "80:8080"

  neqsim-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=1G
    container_name: neqsim-db
    restart: always
    env_file:
      - .secrets
    environment:
      MYSQL_DATABASE: neqsimdatabase
      MYSQL_USER: remote
    volumes:
      - "./data/neqsimdatabase:/var/lib/mysql"
      # Only needed to populate DB
      - "./data/dumps:/temporary"
    # # If you want to connect to the database directly, expose these ports.
    ports:
      - "3306:3306"
  thermo-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=1G
    container_name: thermo-db
    restart: always
    env_file:
      - .secrets
    environment:
      MYSQL_DATABASE: neqsimthermodatabase
      MYSQL_USER: remote
    volumes:
      - "./data/thermodatabase:/var/lib/mysql"
      # Only needed to populate DB
      - "./data/dumps:/temporary"
    # # If you want to connect to the database directly, expose these ports.
    ports:
      - "3307:3306"
  fluidblob-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=1G
    container_name: fluidblob-db
    restart: always
    env_file:
      - .secrets
    environment:
      MYSQL_DATABASE: neqsimblobdb
      MYSQL_USER: remote
    volumes:
      - "./data/neqsimblobdb:/var/lib/mysql"
      # Only needed to populate DB
      - "./data/dumps:/temporary"
    # # If you want to connect to the database directly, expose these ports.
    ports:
      - "3308:3306"
