version: '3.4'
services:

  neqsimweb:
    container_name: neqsimweb
    hostname: neqsimweb
    image: neqsimweb
    build: .
    ports:
      - "80:8080"
    # TODO: This should be compiled with the .war file
    volumes:
       - "./tomcat-conf/META-INF/context.xml:/usr/local/tomcat/webapps/ROOT/META-INF/context.xml"
      #  - "./tomcat-conf/META-INF/context.xml:/usr/local/tomcat/webapps/NeqSimServer3/META-INF/context.xml"

  database:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mintest
      MYSQL_DATABASE: neqsimdatabase
      MYSQL_USER: remote
      # TODO: Use secret and set db connectionstring from ENV
      MYSQL_PASSWORD: remote
    volumes:
      - "./data/database:/var/lib/mysql"
      # Only needed to populate DB 
      - "./data/dumps:/temporary"
    # ports:
    #   - "3306:3306"