version: '3.4'
services:
  # #Need to remove the "SecurityFilter.java" check to make the application be available on the root of the url.
  # proxy:
  #   image: neqsim-proxy
  #   build: ./proxy
  #   ports:
  #     - "80:80"

  neqsimweb:
    container_name: neqsim-web
    hostname: neqsim-web
    image: neqsimweb
    env_file: 
      - .secrets
    environment:
      MYSQL_USER: remote
      MYSQL_URL: jdbc:mysql://database:3306/neqsimdatabase
    build: .
    ports:
      - "80:8080"

  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=325058560
    container_name: neqsim-database
    restart: always
    env_file: 
      - .secrets
    environment:
      MYSQL_DATABASE: neqsimdatabase
      MYSQL_USER: remote
    volumes:
      - "./data/database:/var/lib/mysql"
      # Only needed to populate DB 
      - "./data/dumps:/temporary"
    # # If you want to connect to the database directly, expose these ports.
    # ports:
    #   - "3306:3306"