version: '3.4'
services:

  neqsimweb:
    container_name: neqsimweb
    hostname: neqsimweb
    image: neqsimweb
    build: .
    ports:
      - "80:8080"
    volumes:
       - "./tomcat-conf/META-INF/context.xml:/usr/local/tomcat/webapps/NeqSimServer3/META-INF/context.xml"

  database:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mintest
      MYSQL_DATABASE: neqsimdatabase
      MYSQL_USER: remote
      MYSQL_PASSWORD: remote
    volumes:
      - "./data/database:/var/lib/mysql"
      - "./data/dumps:/temporary"
    ports:
      - "3306:3306"